
export const HTTP_ERROR ="HTTP_ERROR";
 
export const REQUEST_PROCESS_INIT = "REQUEST_PROCESS_INIT";

export const COMPLETE_REQUEST = "COMPLETE_REQUEST";

export const FETCH_GOOGLE_BOOKS = "FETCH_GOOGLE_BOOKS";
